analyticsOS:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: /duckdb_output/warehouse_new.db
      threads: 4
      extensions: ["httpfs", "parquet"]
      settings:
        s3_endpoint: "minio:9000"
        s3_url_style: "path"
        s3_use_ssl: false
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
